# environment configs
num_init_dags: 50
gamma: 0.99
resource_limit: 6000
train_sample: 50
test_sample: 10

# learning configs
batch_size: 1
lr_steps: []
max_timesteps: 5000
k_epochs: 10
update_timestep: 50
learning_rate: 0.001
eps_clip: 0.1

# model parameters
node_output_size: 64
gnn_layers: 5

# test parameters
search_size: 10

# misc configs
log_interval: 1
test_interval: 10 #50
max_episodes: 5000
