# environment configs
solver_type: ipfp
dataset: AIDS-20-30
gamma: 0.95
train_sample: 50
test_sample: 10

# learning configs
batch_size: 1
lr_steps: []
max_timesteps: 10
k_epochs: 10
update_timestep: 10
learning_rate: 0.001
eps_clip: 0.1

# model parameters
node_output_size: 64
gnn_layers: 3

# test parameters
search_size: 3

# misc configs
log_interval: 1
test_interval: 200
max_episodes: 10000
test_model_weight: pretrained/PPO_ipfp_datasetAIDS-20-30_beam3_ratio0.2117.pt
